/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development Based 2015-03-20.2422b18"
#define SSHVER "PuTTY-Snapshot-2015-03-20.2422b18"
#define BINARY_VERSION 0,64,1021,0
